// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJwho8cvIcbXbYkJiDS06veh2PPB-NWn8',
    appId: '1:751966605925:web:ade11d77beac8f83a66c8c',
    messagingSenderId: '751966605925',
    projectId: 'msa-chat-c3724',
    authDomain: 'msa-chat-c3724.firebaseapp.com',
    storageBucket: 'msa-chat-c3724.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh3xMJSVt3OZXDTUATAPG-pnQisO01PH8',
    appId: '1:751966605925:android:e6ca153d185fadb7a66c8c',
    messagingSenderId: '751966605925',
    projectId: 'msa-chat-c3724',
    storageBucket: 'msa-chat-c3724.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2F8mBhLUHmyNz9Mg1RglmTCzfq_5mrVk',
    appId: '1:751966605925:ios:aad797275cc85d1aa66c8c',
    messagingSenderId: '751966605925',
    projectId: 'msa-chat-c3724',
    storageBucket: 'msa-chat-c3724.firebasestorage.app',
    iosBundleId: 'com.example.msaChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2F8mBhLUHmyNz9Mg1RglmTCzfq_5mrVk',
    appId: '1:751966605925:ios:aad797275cc85d1aa66c8c',
    messagingSenderId: '751966605925',
    projectId: 'msa-chat-c3724',
    storageBucket: 'msa-chat-c3724.firebasestorage.app',
    iosBundleId: 'com.example.msaChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJwho8cvIcbXbYkJiDS06veh2PPB-NWn8',
    appId: '1:751966605925:web:3448bd4d9862e858a66c8c',
    messagingSenderId: '751966605925',
    projectId: 'msa-chat-c3724',
    authDomain: 'msa-chat-c3724.firebaseapp.com',
    storageBucket: 'msa-chat-c3724.firebasestorage.app',
  );
}
